// Code generated by goctl. DO NOT EDIT.
// Source: talentrpc.proto

package server

import (
	"context"
	"ginAdminServer/remoterpc/talentrpc/internal/logic"
	"ginAdminServer/remoterpc/talentrpc/internal/svc"
	__ "ginAdminServer/remoterpc/talentrpc/pb"
)

type TalentServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedTalentServer
}

func NewTalentServer(svcCtx *svc.ServiceContext) *TalentServer {
	return &TalentServer{
		svcCtx: svcCtx,
	}
}

func (s *TalentServer) RegisterAdminUser(ctx context.Context, in *__.RegisterReq) (*__.RegisterResp, error) {
	l := logic.NewRegisterAdminUserLogic(ctx, s.svcCtx)
	return l.RegisterAdminUser(in)
}

func (s *TalentServer) GetMenuFromAdminId(ctx context.Context, in *__.GetMenuTreeReq) (*__.GetMenuTreeResp, error) {
	l := logic.NewGetMenuFromAdminIdLogic(ctx, s.svcCtx)
	return l.GetMenuFromAdminId(in)
}
